packages:
  - packages/*
catalog:
  "@ai-sdk/openai": ^1.3.22
  "@ai-sdk/react": ^1.2.12
  "@biomejs/biome": ^1.9.4
  "@cloudflare/vite-plugin": ^1.7.5
  "@cloudflare/vitest-pool-workers": ^0.8.47
  "@cloudflare/workers-oauth-provider": ^0.0.5
  "@cloudflare/workers-types": ^4.20250627.0
  "@modelcontextprotocol/sdk": ^1.13.2
  "@radix-ui/react-accordion": ^1.2.11
  "@radix-ui/react-slot": ^1.2.3
  "@sentry/cloudflare": ^9.33.0
  "@sentry/core": ^9.33.0
  "@sentry/node": ^9.33.0
  "@sentry/react": ^9.33.0
  "@sentry/vite-plugin": ^3.5.0
  "@tailwindcss/typography": ^0.5.16
  "@tailwindcss/vite": ^4.1.11
  "@types/node": ^22.15.33
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
  "@vitejs/plugin-react": ^4.6.0
  "@vitest/coverage-v8": ^3.2.4
  agents: ~0.0.99
  ai: ^4.3.16
  better-sqlite3: ^11.10.0
  chalk: ^5.4.1
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  commander: ^14.0.0
  dotenv: ^16.6.1
  dotenv-cli: ^8.0.0
  hono: ^4.8.3
  lint-staged: ^15.5.2
  lucide-react: ^0.503.0
  msw: ^2.10.2
  open: ^10.1.2
  react: ^19.1.0
  react-dom: ^19.1.0
  react-markdown: ^9.1.0
  remark-gfm: ^4.0.1
  simple-git-hooks: ^2.13.0
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.11
  tsdown: ^0.12.9
  tsx: ^4.20.3
  turbo: ^2.5.4
  tw-animate-css: ^1.3.4
  typescript: ^5.8.3
  vite: ^6.3.5
  vitest: ^3.2.4
  vitest-evals: ^0.4.0
  workers-mcp: 0.1.0-3
  wrangler: ^4.22.0
  zod: ^3.25.67
  zod-to-json-schema: ^3.24.6
