/**
 * Post-build script that reads bundled HTML apps and generates
 * TypeScript/JavaScript exports for consumption by other packages.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";

const DIST_DIR = join(dirname(new URL(import.meta.url).pathname), "..", "dist");
const APPS_DIR = join(DIST_DIR, "apps");

// Map of app names to their bundled HTML file
// Vite outputs HTML files in nested directories preserving the source structure
const APPS = {
  searchEventsChart: "src/apps/search-events-chart/index.html",
};

function main() {
  // Ensure dist directory exists
  if (!existsSync(DIST_DIR)) {
    mkdirSync(DIST_DIR, { recursive: true });
  }

  // Read bundled HTML files and generate exports
  const exports: Record<string, string> = {};

  for (const [exportName, fileName] of Object.entries(APPS)) {
    const htmlPath = join(APPS_DIR, fileName);

    if (!existsSync(htmlPath)) {
      console.error(`Warning: ${htmlPath} not found. Skipping.`);
      continue;
    }

    const htmlContent = readFileSync(htmlPath, "utf-8");
    exports[exportName] = htmlContent;
    console.log(`Bundled ${fileName} -> ${exportName}Html`);
  }

  // Generate JavaScript module
  const jsContent = `// Auto-generated by bundle-apps.ts - do not edit manually
${Object.entries(exports)
  .map(
    ([name, content]) =>
      `export const ${name}Html = ${JSON.stringify(content)};`,
  )
  .join("\n")}

// Re-export shared types and utilities
export { inferChartType } from "./shared/chart-data.js";
`;

  writeFileSync(join(DIST_DIR, "index.js"), jsContent);
  console.log("Generated dist/index.js");

  // Generate TypeScript declarations
  const dtsContent = `// Auto-generated by bundle-apps.ts - do not edit manually
${Object.keys(exports)
  .map((name) => `export declare const ${name}Html: string;`)
  .join("\n")}

// Re-export shared types
export type { ChartData, ChartType } from "./shared/chart-data.js";
export { inferChartType } from "./shared/chart-data.js";
`;

  writeFileSync(join(DIST_DIR, "index.d.ts"), dtsContent);
  console.log("Generated dist/index.d.ts");
}

main();
