/**
 * Modern Sentry User Feedback types and output schemas.
 */

import type { EventAttachmentDetailsResponse } from "@sentry/api";
import { zEventAttachmentDetailsResponse } from "@sentry/api/zod";
import { z } from "zod";
import type { SentryEvent, SentryIssue } from "./sentry.js";
import { SentryIssueSchema } from "./sentry.js";

/** Metadata stored on a modern Feedback issue group. */
export type FeedbackMetadata = {
  /** Feedback message submitted by the end user. */
  message: string;
  /** End-user email address, or null when omitted. */
  contact_email?: string | null;
  /** End-user display name, or null when omitted. */
  name?: string | null;
  /** Feedback title generated by Sentry. */
  title?: string;
  /** Search/display value generated by Sentry. */
  value?: string;
  /** Initial numeric priority assigned when the Feedback issue was created. */
  initial_priority?: number;
  /** Capture source such as `new_feedback_envelope`. */
  source?: string | null;
  /** AI-generated feedback summary, when available. */
  summary?: string | null;
  /** SDK that captured the feedback. */
  sdk?: {
    /** Raw SDK name. */
    name: string;
    /** Normalized SDK name used by Sentry. */
    name_normalized?: string;
  };
  /** Associated error event ID included by list responses. */
  associated_event_id?: string;
  /** Additional fields returned by newer Sentry versions. */
  [key: string]: unknown;
};

/** Modern User Feedback represented as a category-constrained Sentry issue. */
export type SentryFeedback = Omit<
  SentryIssue,
  "issueCategory" | "issueType" | "metadata"
> & {
  /** Discriminator for the issue category. */
  issueCategory: "feedback";
  /** Discriminator for the issue type. */
  issueType: "feedback";
  /** Feedback-specific issue metadata. */
  metadata: FeedbackMetadata;
  /** Whether the current user has read the feedback. */
  hasSeen?: boolean;
  /** Whether the latest event contains attachments. */
  latestEventHasAttachments?: boolean;
};

/** Data yielded by `feedback list` for human and JSON rendering. */
export type FeedbackListResult = {
  /** Feedback items on the current page. */
  feedback: SentryFeedback[];
  /** Whether a following page is available. */
  hasMore: boolean;
  /** Whether a previous page is available. */
  hasPrev: boolean;
  /** Server cursor for the following page. */
  nextCursor?: string | null;
  /** Resolved organization slug. */
  org: string;
  /** Resolved project slug, absent for organization-wide queries. */
  project?: string;
};

/** Data yielded by `feedback view` before JSON flattening. */
export type FeedbackViewResult = {
  /** Resolved organization slug, or null when unavailable. */
  org: string | null;
  /** The modern Feedback issue. */
  feedback: SentryFeedback;
  /** Latest event for the Feedback issue. */
  event: SentryEvent | null;
  /** Related Session Replay IDs. */
  replayIds: string[];
  /** Attachments on the latest Feedback event. */
  attachments: EventAttachmentDetailsResponse[];
};

/** Documentation schema for Feedback metadata. */
export const FeedbackMetadataSchema = z
  .object({
    message: z.string().describe("Feedback message"),
    contact_email: z
      .string()
      .nullable()
      .optional()
      .describe("End-user email address"),
    name: z.string().nullable().optional().describe("End-user display name"),
    title: z.string().optional().describe("Feedback title"),
    value: z.string().optional().describe("Feedback display value"),
    initial_priority: z
      .number()
      .optional()
      .describe("Initial priority assigned when the feedback was created"),
    source: z
      .string()
      .nullable()
      .optional()
      .describe("Feedback capture source"),
    summary: z.string().nullable().optional().describe("AI-generated summary"),
    sdk: z
      .object({
        name: z.string().describe("SDK name"),
        name_normalized: z.string().optional().describe("Normalized SDK name"),
      })
      .optional()
      .describe("SDK that captured the feedback"),
    associated_event_id: z
      .string()
      .optional()
      .describe("Associated error event ID"),
  })
  .passthrough()
  .describe("Feedback metadata");

/** Documentation schema for a modern Feedback issue. */
export const SentryFeedbackSchema = SentryIssueSchema.extend({
  issueCategory: z.literal("feedback").describe("Issue category discriminator"),
  issueType: z.literal("feedback").describe("Issue type discriminator"),
  metadata: FeedbackMetadataSchema,
  hasSeen: z
    .boolean()
    .optional()
    .describe("Whether the feedback has been read"),
  latestEventHasAttachments: z
    .boolean()
    .optional()
    .describe("Whether the latest event has attachments"),
}).describe("Sentry User Feedback");

/** Documentation schema for flattened `feedback view` JSON output. */
export const FeedbackViewOutputSchema = SentryFeedbackSchema.extend({
  org: z.string().nullable().describe("Organization slug"),
  event: z.unknown().nullable().describe("Latest feedback event"),
  replayIds: z.array(z.string()).describe("Related Session Replay IDs"),
  attachments: z
    .array(zEventAttachmentDetailsResponse)
    .describe("Attachments on the latest feedback event"),
}).describe("Feedback view output");
