/*!
 * Cozette bitmap font subset, version 1.30.0.
 * Copyright (c) 2020, Ines <ines@moonwit.ch>
 * https://github.com/the-moonwitch/Cozette
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import { Buffer } from "node:buffer";

/** Cozette's native monospaced cell width. */
export const COZETTE_CELL_WIDTH = 6;

/** Cozette's native cell height, including descenders. */
export const COZETTE_CELL_HEIGHT = 13;

const FIRST_ASCII_CODE_POINT = 32;
const LAST_ASCII_CODE_POINT = 126;
const FULL_BLOCK_CODE_POINT = 0x25_88;
const BLACK_SQUARE_CODE_POINT = 0x25_a0;
const UPPER_HALF_BLOCK_CODE_POINT = 0x25_80;
const LOWER_HALF_BLOCK_CODE_POINT = 0x25_84;
const HORIZONTAL_RULE_CODE_POINT = 0x25_00;
const VERTICAL_RULE_CODE_POINT = 0x25_02;
const LOWER_LEFT_CORNER_CODE_POINT = 0x25_14;
const RIGHT_TEE_CODE_POINT = 0x25_24;
const DOWN_TEE_CODE_POINT = 0x25_2c;
const ELLIPSIS_CODE_POINT = 0x20_26;
const LIGHT_SHADE_CODE_POINT = 0x25_91;
const MEDIUM_SHADE_CODE_POINT = 0x25_92;
const DARK_SHADE_CODE_POINT = 0x25_93;
const LOWER_ONE_EIGHTH_BLOCK_CODE_POINT = 0x25_81;
const LOWER_TWO_EIGHTHS_BLOCK_CODE_POINT = 0x25_82;
const LOWER_THREE_EIGHTHS_BLOCK_CODE_POINT = 0x25_83;
const LOWER_FIVE_EIGHTHS_BLOCK_CODE_POINT = 0x25_85;
const LOWER_SIX_EIGHTHS_BLOCK_CODE_POINT = 0x25_86;
const LOWER_SEVEN_EIGHTHS_BLOCK_CODE_POINT = 0x25_87;
const FULL_BLOCK_INDEX = LAST_ASCII_CODE_POINT - FIRST_ASCII_CODE_POINT + 1;
const BLACK_SQUARE_INDEX = FULL_BLOCK_INDEX + 1;
const QUESTION_MARK_INDEX = 0x3f - FIRST_ASCII_CODE_POINT;

/** Dashboard's compact number and table renderers use these block glyphs. */
const UPPER_HALF_BLOCK_GLYPH = new Uint8Array([
  63, 63, 63, 63, 63, 63, 0, 0, 0, 0, 0, 0, 0,
]);
const LOWER_HALF_BLOCK_GLYPH = new Uint8Array([
  0, 0, 0, 0, 0, 0, 63, 63, 63, 63, 63, 63, 63,
]);
const HORIZONTAL_RULE_GLYPH = new Uint8Array([
  0, 0, 0, 0, 0, 0, 63, 0, 0, 0, 0, 0, 0,
]);
const VERTICAL_RULE_GLYPH = new Uint8Array([
  8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
]);
const LOWER_LEFT_CORNER_GLYPH = new Uint8Array([
  32, 32, 32, 32, 32, 32, 63, 0, 0, 0, 0, 0, 0,
]);
const RIGHT_TEE_GLYPH = new Uint8Array([
  1, 1, 1, 1, 1, 1, 63, 1, 1, 1, 1, 1, 1,
]);
const DOWN_TEE_GLYPH = new Uint8Array([0, 0, 0, 0, 0, 63, 8, 8, 8, 8, 8, 8, 8]);
const ELLIPSIS_GLYPH = new Uint8Array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 42, 0, 0]);
const LIGHT_SHADE_GLYPH = new Uint8Array([
  33, 0, 0, 33, 0, 0, 33, 0, 0, 33, 0, 0, 33,
]);
const MEDIUM_SHADE_GLYPH = new Uint8Array([
  36, 9, 36, 9, 36, 9, 36, 9, 36, 9, 36, 9, 36,
]);
const DARK_SHADE_GLYPH = new Uint8Array([
  45, 54, 45, 54, 45, 54, 45, 54, 45, 54, 45, 54, 45,
]);
const LOWER_ONE_EIGHTH_BLOCK_GLYPH = new Uint8Array([
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 63, 63,
]);
const LOWER_TWO_EIGHTHS_BLOCK_GLYPH = new Uint8Array([
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 63, 63, 63,
]);
const LOWER_THREE_EIGHTHS_BLOCK_GLYPH = new Uint8Array([
  0, 0, 0, 0, 0, 0, 0, 0, 63, 63, 63, 63, 63,
]);
const LOWER_FIVE_EIGHTHS_BLOCK_GLYPH = new Uint8Array([
  0, 0, 0, 0, 0, 63, 63, 63, 63, 63, 63, 63, 63,
]);
const LOWER_SIX_EIGHTHS_BLOCK_GLYPH = new Uint8Array([
  0, 0, 0, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
]);
const LOWER_SEVEN_EIGHTHS_BLOCK_GLYPH = new Uint8Array([
  0, 0, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63,
]);

/** Raster glyphs needed by the dashboard's box, sparkline, and text output. */
const DASHBOARD_GLYPHS = new Map<number, Uint8Array>([
  [UPPER_HALF_BLOCK_CODE_POINT, UPPER_HALF_BLOCK_GLYPH],
  [LOWER_HALF_BLOCK_CODE_POINT, LOWER_HALF_BLOCK_GLYPH],
  [HORIZONTAL_RULE_CODE_POINT, HORIZONTAL_RULE_GLYPH],
  [VERTICAL_RULE_CODE_POINT, VERTICAL_RULE_GLYPH],
  [LOWER_LEFT_CORNER_CODE_POINT, LOWER_LEFT_CORNER_GLYPH],
  [RIGHT_TEE_CODE_POINT, RIGHT_TEE_GLYPH],
  [DOWN_TEE_CODE_POINT, DOWN_TEE_GLYPH],
  [ELLIPSIS_CODE_POINT, ELLIPSIS_GLYPH],
  [LIGHT_SHADE_CODE_POINT, LIGHT_SHADE_GLYPH],
  [MEDIUM_SHADE_CODE_POINT, MEDIUM_SHADE_GLYPH],
  [DARK_SHADE_CODE_POINT, DARK_SHADE_GLYPH],
  [LOWER_ONE_EIGHTH_BLOCK_CODE_POINT, LOWER_ONE_EIGHTH_BLOCK_GLYPH],
  [LOWER_TWO_EIGHTHS_BLOCK_CODE_POINT, LOWER_TWO_EIGHTHS_BLOCK_GLYPH],
  [LOWER_THREE_EIGHTHS_BLOCK_CODE_POINT, LOWER_THREE_EIGHTHS_BLOCK_GLYPH],
  [LOWER_FIVE_EIGHTHS_BLOCK_CODE_POINT, LOWER_FIVE_EIGHTHS_BLOCK_GLYPH],
  [LOWER_SIX_EIGHTHS_BLOCK_CODE_POINT, LOWER_SIX_EIGHTHS_BLOCK_GLYPH],
  [LOWER_SEVEN_EIGHTHS_BLOCK_CODE_POINT, LOWER_SEVEN_EIGHTHS_BLOCK_GLYPH],
]);

/**
 * Printable ASCII, full block, and black square raster rows generated from
 * Cozette's v1.30.0 BDF release. Each glyph has 13 rows packed into the low
 * six bits of a byte, with bit 5 as the leftmost pixel. Source SHA-256:
 * 8d740166af3a14053773ac7a8846bf288c8818a44f73ab28d4725d91b03a5639.
 */
const GLYPH_ROWS = Uint8Array.from(
  Buffer.from(
    "AAAAAAAAAAAAAAAAAAAABAQEBAQEAAQAAAAACgoKAAAAAAAAAAAAAAAKCh8KCh8KCgAAAAAEDhUUDgUFFQ4EAAAACBQJAgQIEgUCAAAAAAQKCgQNEhISDQAAAAAEBAQAAAAAAAAAAAAAAgQECAgICAgEBAIAAAgEBAICAgICBAQIAAAAAAAKBB8ECgAAAAAAAAAABAQfBAQAAAAAAAAAAAAAAAAMDAQIAAAAAAAAAB8AAAAAAAAAAAAAAAAAAAwMAAAAAAEBAgIEBAgIEBAAAAAADhERFRUREQ4AAAAAAAQMFAQEBAQfAAAAAAAOEQECBAgQHwAAAAAADhEBBgEBEQ4AAAAAAAEDBQkRHwEBAAAAAAAfEBAeAQERDgAAAAAABggQHhEREQ4AAAAAAB8BAgIEBAgIAAAAAAAOEREOERERDgAAAAAADhEREQ8BAgwAAAAAAAAADAwAAAwMAAAAAAAAAAwMAAAMDAQIAAAAAAECBAgEAgEAAAAAAAAAAB8AHwAAAAAAAAAAEAgEAgQIEAAAAAAADhEBAgQEAAQAAAAAAA4RERcVFxAPAAAAAAAOERERHxEREQAAAAAAHhERHhERER4AAAAAAA4REBAQEBEOAAAAAAAcEhERERESHAAAAAAAHxAQHhAQEB8AAAAAAB8QEB4QEBAQAAAAAAAOERAQExERDgAAAAAAERERHxEREREAAAAAAA4EBAQEBAQOAAAAAAAHAQEBARERDgAAAAAAERIUHBISEREAAAAAABAQEBAQEBAfAAAAAAARGxUVEREREQAAAAAAERkZFRUTExEAAAAAAA4REREREREOAAAAAAAeERERHhAQEAAAAAAADhEREREREg0BAAAAAB4RER4SERERAAAAAAAOERAOAQERDgAAAAAAHwQEBAQEBAQAAAAAABEREREREREOAAAAAAAREREKCgoEBAAAAAAAERERFRUOCgoAAAAAABERCgQEChERAAAAAAAREREKBAQEBAAAAAAAHwIEBAgIEB8AAAAADggICAgICAgICA4AABAQCAgEBAICAQEAAAAOAgICAgICAgICDgAEChEAAAAAAAAAAAAAAAAAAAAAAAAAAB8AAAAIBAAAAAAAAAAAAAAAAAAADxERERMNAAAAABAQEB4RERERHgAAAAAAAAAOERAQEQ4AAAAAAQEBDxEREREPAAAAAAAAAA4RHxARDgAAAAAHCAgeCAgICAgAAAAAAAAADxEREREPAQEOABAQEB4REREREQAAAAAABAAMBAQEBAMAAAAAAAIABgICAgICCgQAABAQEBESFBwSEQAAAAAMBAQEBAQEBAYAAAAAAAAAGhUVFRUVAAAAAAAAAB4REREREQAAAAAAAAAOEREREQ4AAAAAAAAAHhEREREeEBAQAAAAAA8RERERDwEBAQAAAAAeERAQEBAAAAAAAAAADxAOAQEeAAAAAAAICB4ICAgIBwAAAAAAAAAREREREQ8AAAAAAAAAEREKCgQEAAAAAAAAABERFRUKCgAAAAAAAAARCgQEChEAAAAAAAAAEREREREPAQEOAAAAAB8CBAgQHwAAAAADBAQEBBgEBAQEAwAABAQEBAQEBAQEBAQAABgEBAQEAwQEBAQYAAAAAAAACRUSAAAAAAA/Pz8/Pz8/Pz8/Pz8/AAAAPz8/Pz8/PwAAAA==",
    "base64"
  )
);

/** Look up a Cozette glyph by character without parsing or rasterizing a font. */
export function getCozetteGlyph(character: string): Uint8Array {
  const codePoint = character.codePointAt(0);
  const dashboardGlyph = getDashboardGlyph(codePoint);
  if (dashboardGlyph) {
    return dashboardGlyph;
  }
  const index = getGlyphIndex(codePoint);
  const start = (index ?? QUESTION_MARK_INDEX) * COZETTE_CELL_HEIGHT;
  return GLYPH_ROWS.subarray(start, start + COZETTE_CELL_HEIGHT);
}

/** Whether the embedded font can represent a character without substitution. */
export function hasCozetteGlyph(character: string): boolean {
  const codePoint = character.codePointAt(0);
  return (
    getDashboardGlyph(codePoint) !== undefined ||
    getGlyphIndex(codePoint) !== undefined
  );
}

function getDashboardGlyph(
  codePoint: number | undefined
): Uint8Array | undefined {
  return codePoint === undefined ? undefined : DASHBOARD_GLYPHS.get(codePoint);
}

function getGlyphIndex(codePoint: number | undefined): number | undefined {
  if (
    codePoint !== undefined &&
    codePoint >= FIRST_ASCII_CODE_POINT &&
    codePoint <= LAST_ASCII_CODE_POINT
  ) {
    return codePoint - FIRST_ASCII_CODE_POINT;
  }
  if (codePoint === FULL_BLOCK_CODE_POINT) {
    return FULL_BLOCK_INDEX;
  }
  if (codePoint === BLACK_SQUARE_CODE_POINT) {
    return BLACK_SQUARE_INDEX;
  }
}
