/** Returns the first text content item from an MCP tool result. */
export function getTextContent(result: unknown): string {
  const content = (result as { content?: unknown }).content;
  if (!Array.isArray(content)) {
    return "";
  }
  return content?.find((item) => typeof item.text === "string")?.text ?? "";
}

/** Returns structuredContent after checking the result has an object payload. */
export function getStructuredContent<T extends Record<string, unknown>>(
  result: unknown,
): T {
  const structuredContent = (result as { structuredContent?: unknown })
    .structuredContent;
  if (
    !structuredContent ||
    typeof structuredContent !== "object" ||
    Array.isArray(structuredContent)
  ) {
    throw new Error(`No structuredContent found: ${JSON.stringify(result)}`);
  }

  return structuredContent as T;
}

/** Asserts a handler returned structuredContent without handwritten content. */
export function assertStructuredOnlyResult(result: unknown): void {
  getStructuredContent(result);
  if ("content" in Object(result)) {
    throw new Error(
      `Expected structured-only result without content: ${JSON.stringify(result)}`,
    );
  }
}

/** Returns the JSON text fallback generated by the server for structuredContent. */
export function getGeneratedTextFromStructuredContent(result: unknown): string {
  return JSON.stringify(getStructuredContent(result), null, 2);
}
