name: Canary Cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  deployments: write

jobs:
  cleanup:
    name: Mark Canary Deployment Inactive
    runs-on: ubuntu-latest
    
    steps:
      - name: Mark Deployments as Inactive
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Find all deployments for this PR
            const deployments = await github.rest.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha,
              environment: 'canary'
            });
            
            console.log(`Found ${deployments.data.length} deployments to mark inactive`);
            
            // Mark each deployment as inactive
            for (const deployment of deployments.data) {
              try {
                await github.rest.repos.createDeploymentStatus({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  deployment_id: deployment.id,
                  state: 'inactive',
                  description: 'PR closed - worker deleted',
                  auto_inactive: false
                });
                console.log(`Marked deployment ${deployment.id} as inactive`);
              } catch (error) {
                console.error(`Failed to mark deployment ${deployment.id} as inactive:`, error);
              }
            }