name: Issue Triage

on:
  issues:
    types: [opened]

jobs:
  triage:
    permissions:
      contents: read
    uses: getsentry/.github/.github/workflows/issue-triage.yml@main
    with:
      issue-number: ${{ github.event.issue.number }}
      repository: ${{ github.repository }}
    secrets: inherit
