name: Preview Cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:
  cleanup:
    name: Delete Preview Environment
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # pnpm/action-setup@v4
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        name: Install pnpm
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Generate Environment Name
        id: env_name
        run: |
          # Get branch name and construct environment name (same as deploy)
          BRANCH_NAME="${{ github.head_ref }}"
          # Must match the naming in preview-deploy.yml
          ENV_SUFFIX=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9]/-/g' | tr '[:upper:]' '[:lower:]' | cut -c1-10)
          ENV_NAME="preview-${ENV_SUFFIX}"
          
          echo "env_name=$ENV_NAME" >> $GITHUB_OUTPUT
          echo "Deleting preview environment: $ENV_NAME"

      - name: Delete Preview Environment
        uses: cloudflare/wrangler-action@v3
        continue-on-error: true  # Don't fail if environment doesn't exist
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: packages/mcp-cloudflare
          command: delete --env ${{ steps.env_name.outputs.env_name }} --force
          packageManager: pnpm