name: Preview Cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:
  cleanup:
    name: Delete Preview Environment
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # pnpm/action-setup@v4
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        name: Install pnpm
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Generate Worker Name
        id: worker_name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          WORKER_NAME=$(./scripts/generate-worker-name.sh "$BRANCH_NAME")
          
          echo "worker_name=$WORKER_NAME" >> $GITHUB_OUTPUT
          echo "Deleting preview worker: $WORKER_NAME"

      - name: Delete Preview Worker
        uses: cloudflare/wrangler-action@v3
        continue-on-error: true  # Don't fail if worker doesn't exist
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: packages/mcp-cloudflare
          command: delete --name ${{ steps.worker_name.outputs.worker_name }} --force
          packageManager: pnpm